### ISSUE TITLE
Cell height issue for entries tabs

### ISSUE THREAD

**Issue by jlachancekffein** [chasegiunta/craft-jason#1]
Hi, 

We are using your plugin to manage i18n text for your client.

It seem to have a issue with the table cell height when the plugin field is inside another tab not active on page load.

On load of an entry in the control panel, if the tab containing the jason field is active, the cell height is correct. But if we load an entry with any other tab active and then change the tab to show the jason field, the jason table cell show only one line. We have to reload to show the table correctly.

Here the correct behavior (Tab is active on page load)

![image](https://user-images.githubusercontent.com/24896469/58352000-4d338080-7e38-11e9-97a0-1fcf6911205d.png)

Here is the problem (Change tab after page load)

![image](https://user-images.githubusercontent.com/24896469/58352114-94217600-7e38-11e9-8003-5b50722e29aa.png)

Take note that resizing the window fix the problem.

Thanks for your plugin.

**Comment by chasegiunta** [comment]
@jlachancekffein thanks for reporting - released a fix.
