### ISSUE TITLE
Database Field Type

### ISSUE THREAD

**Issue by jordancraftltd** [chasegiunta/craft-jason#139]
Hi Chase,

Thanks for the excellent plugin.

Is it possible to change the field type to mediumtext after I encountered this error?

![image](https://user-images.githubusercontent.com/62548371/136931250-e61ed77b-2a0c-4e80-8fdf-60c7a0a81029.png)

Many thanks

**Comment by lassemt** [comment]
YII doesn't support it atm. because of backward and DB driver compatibility:
https://github.com/yiisoft/db-mysql/issues/2

Another relevant thread: 
https://github.com/craftcms/cms/discussions/9040
