### ISSUE TITLE
Craft 4 support

### ISSUE THREAD

**Issue by jerome2710** [chasegiunta/craft-jason#142]
Any chance this plugin will include Craft 4 support in the near future, @chasegiunta? Otherwise we need to look into alternatives to update our sites.

**Comment by chasegiunta** [comment]
@jerome2710 I'll be taking a crack at it soon.

**Comment by chasegiunta** [comment]
Sorry for the delay. Still going to do this. I've migrated one of my other easier plugins to figure out what's necessary. Jason is a bit more involved but it will be done.

**Comment by jerome2710** [comment]
@chasegiunta any updates regarding this matter? Could you provide us with a timeline?

**Comment by chasegiunta** [comment]
@jerome2710 I'll be taking time off work the first two weeks of September and plan on getting it done then. Apologies for the delay.

**Comment by rostockahoi** [comment]
Hey @chasegiunta, need any help with that? I already migrated a plugin to 4 a little while ago.

**Comment by chasegiunta** [comment]
Well, I had planned some larger updates with 4.0.0, but I can't get to them at the moment. I have a newborn that's been occupying my time. That being said, it's been updated for 4.0 compatibility. Please give it a spin and report any issues that may arise. Apologies to all for the delay.

**Comment by rostockahoi** [comment]
Thanks for that one @chasegiunta. I'll try it out and will report. Keep your chin up! 👍
