### ISSUE TITLE
 Is there a reason why php8.1 is required ?

### ISSUE THREAD

**Issue by jlachancekffein** [chasegiunta/craft-jason#144]
Is there a reason why php8.1 is required in composer requirements?

```
"require": {
    "craftcms/cms": "^4.0.0",
    "php": "^8.1.0"
},
```

Because Craft requirements are

```
"require": {
    "php": "^8.0.2",
   ....
```

I ask because we cannot use version 8.1 at the moment. So I can't use the plugin.

Is it possible for you to follow Craft's requirements or is there a specific reason for using php 8.1?

**Comment by chasegiunta** [comment]
@jlachancekffein I can't say why I did that. Maybe I was under the impression 8.1 was minimum for Craft CMS 4. If you want to test on 8.1 and PR the change I'll merge & release.
