### ISSUE TITLE
Jason field trigger modification entry automatically

### ISSUE THREAD

**Issue by jlachancekffein** [chasegiunta/craft-jason#18]
When a jason field is added to a section, it trigger field modification warning automatically even if no modification is made to the entry.

** Step to reproduce
Edit detail entry. Reload the page or click another navigation item. The modification warning popup. 

![Capture d’écran 2019-05-31 à 10 23 17](https://user-images.githubusercontent.com/24896469/58712215-24f2d700-838e-11e9-8729-74ba2025ee90.png)

I understand the message will show if I change something on the jason field but it's not always the case.

Thank you.

**Comment by chasegiunta** [comment]
Thanks. I've been aware of this, just haven't been able to dig in. Somehow, I'll have to figure out how to disable that on Craft's side. Will take a look when I get the chance.

**Comment by jlachancekffein** [comment]
Thanks for your feedback.  :)

**Comment by renzo-s** [comment]
This issue will also produce a new draft (v3.2 feature) whenever an entry is opened, making it basically unusable from this version onwards.

**Comment by renzo-s** [comment]
Fixed with Craft > 3.2.3 not auto-creating drafts anymore.

**Comment by chasegiunta** [comment]
@renzo-s maybe the point you brought up is fixed, but I'm sure the original issue is still there (field is always seen as edited, thus throwing the dialog before leaving). I just haven't had the time to dig in thoroughly and fix it yet

**Comment by ArtDepartmentMJ** [comment]
This issue is still present
