### ISSUE TITLE
js error on field creation

### ISSUE THREAD

**Issue by jlachancekffein** [chasegiunta/craft-jason#26]
For an unknown reason, the Jason plugin returns a javascript error when creating fields: Uncaught TypeError: Can not read property 'call' of undefined.

The only way to fix the problem is to disable the plugin, or to comment $this->js in the file assetbundles/jasonfield /JasonFieldAsset.php

For the moment, it is impossible to save the field since the lightswitch is not displayed and must be required.

See image below for more information.

![Capture d’écran 2019-06-18 à 10 55 18](https://user-images.githubusercontent.com/24896469/59695209-db8cef00-91b7-11e9-95b2-17b26a496a9d.png)

Maybe is related to the Craft version : 3.1.30

**Comment by chasegiunta** [comment]
@jlachancekffein ?

**Comment by jlachancekffein** [comment]
I tried to remove the plugin and then reinstall but the problem occurs again.

See the picture below :

![Capture d’écran 2019-06-19 à 10 44 58](https://user-images.githubusercontent.com/24896469/59775497-540ab300-927f-11e9-869c-78e4337855bb.png)

bootstrap: 78 seems to loader from webpack. webpack: /// webpack / bootstrap.

Is it possible that the js code is not compiling correctly?

**Comment by chasegiunta** [comment]
@jlachancekffein Will definitely try and troubleshoot more, but for the moment, I'm not able to reproduce this with everything up to date.

![image](https://user-images.githubusercontent.com/1377169/59782602-eca33200-9283-11e9-88c2-1283e06b846c.png)

Could you try installing the plugin on a clean install and see if you have issues?

I wonder if it's possible that your browser is trying to load an cached asset file?
