### ISSUE TITLE
The Jason field does not work properly when associated with a Resource type field

### ISSUE THREAD

**Issue by jlachancekffein** [chasegiunta/craft-jason#52]
When a Jason type field is associated with a Resource, the field does not work properly.

In the assets sections, to display the details of an asset, with the double click, the field jason is displayed correctly.

However, if you close the modal window and open the same or another asset, the Jason field is not displayed.

No error appears javascript is displayed in the console.

Probably this field was not thought for this kind of display.

Would it be possible to solve this problem?

Thank you !

![image](https://user-images.githubusercontent.com/24896469/66057991-9b077600-e507-11e9-8cfd-c3a17714717e.png)

![image](https://user-images.githubusercontent.com/24896469/66058035-ab1f5580-e507-11e9-8db3-2e4083d310dc.png)

**Comment by jlachancekffein** [comment]
OK, I understand that you no longer support this plugin.

We will look at the other options.

Thank you.

**Comment by chasegiunta** [comment]
Sorry @jlachancekffein - too many other higher priorities at the moment.
