### ISSUE TITLE
Field setting js broken in Matrix Block

### ISSUE THREAD

**Issue by timkelty** [chasegiunta/craft-jason#66]
![Screen Shot 2020-02-20 at 10 02 15 AM](https://user-images.githubusercontent.com/18329/74947080-52722b80-53c8-11ea-9e3a-bd03de01f137.png)

When adding the field to a Matrix Block, the lightswitches don't show.

`<jason-switch>` is left rendered in the template, so I suspect you just need to make sure your component is mounting within Matrix.

Note: if you try save the field at this point, it will reload with an error because those fields are required – but at that point the switches render, so you can set the values.

**Comment by chasegiunta** [comment]
Hey Tim, thanks for the heads up! Jason definitely needs some love, especially with 3.4. It's encouraging to know that *you* (I've used plenty of your work before!) are using it.

I'm going to try and get an update out for it this weekend and see if I'm smart enough to address some of these issues you and others have reported. 👍

**Comment by timkelty** [comment]
Hah!
I was using a text field for a cheap way for clients to pass in params to Algolia and found this plugin, wondered if someone had built a json editor, and voilà!

Thanks for the work! 🥂

**Comment by timkelty** [comment]
…also hard to not give it a shot with such a great icon :)

**Comment by chasegiunta** [comment]
Sorry for the long wait, should be fixed now!
