### ISSUE TITLE
Formatting JSON using GraphQL

### ISSUE THREAD

**Issue by rlapierre-kffein** [chasegiunta/craft-jason#67]
I would like to know if there a way to make a directive that convert a string to a formatted JSON. I’m using this plugin to get a JSON structure. When querying the corresponding field GraphQL expect a value of type String but it received an StdClass. I tried to cast it using a custom directive JsonFormatter but it doesn’t seems to work.
Is there a way to update this plugin to make it compatible with GraphQL using a GraphQL directive or by updating the plugin itself?

**Comment by chasegiunta** [comment]
@rlapierre-kffein oof, I have no experience with GraphQL, and wouldn't know where to begin. I'd be more than happy to merge a PR though, if you have an idea how to fix it for your use-case...

**Comment by rlapierre-kffein** [comment]
Hi thanks for your quick reply!
Using your plugin on a GraphQL instance I'm getting this data structure. I'm looking for a way to format this JSON inside the GraphQL query. I started to make a directive for it (JsonFormatter) but it always returning an StdClass. I'm still troubleshooting.

`{
  "data": {
    "globalSets": [
      {
        "id": "2",
        "title": null,
        "commons_i18n": "{\r\n \"section\": {\r\n  \"global_experience\": {\r\n   \"title\": \"Boutique experience.\\nGlobal agency resources.\",\r\n   \"cta\": {\r\n    \"label\": \"Contact\",\r\n    \"url\": \"fr/contact\"\r\n   }\r\n  },\r\n  \"footer\": {\r\n   \"privacy_policy\": \"Politique de confidentialité\"\r\n  },\r\n  \"careers\": {\r\n   \"form\": {\r\n    \"title\": \"Envoyer nous votre CV\",\r\n    \"name\": \"Votre nom\",\r\n    \"email\": \"Votre courriel\",\r\n    \"message\": \"Votre message\",\r\n    \"resume\": \"Votre résumé\",\r\n    \"file\": \"Choisir un fichier\",\r\n    \"submit\": \"Soumettre\"\r\n   }\r\n  }\r\n }\r\n}"
      }
    ]
  }
}`

**Comment by chasegiunta** [comment]
@rlapierre-kffein Did you ever tackle this? I may ask for some help with some GraphQL friends to see the route to take here
