### ISSUE TITLE
Issues with multiple Jason fields on a single edit screen

### ISSUE THREAD

**Issue by timkelty** [chasegiunta/craft-jason#74]
FIeld output is empty when adding multiples:
<img width="356" alt="Screen Shot 2020-04-21 at 7 15 58 AM" src="https://user-images.githubusercontent.com/18329/79860036-f9128280-839f-11ea-8474-119f8286950a.png">

**Comment by chasegiunta** [comment]
Working on a new update of Jason out soon which address this.

**Comment by chasegiunta** [comment]
Should be fixed!
