### ISSUE TITLE
Unable to create field in 3.5 beta

### ISSUE THREAD

**Issue by chrisrowe** [chasegiunta/craft-jason#75]
CP errors with `Couldn’t save field`, field options also aren't showing but think that's a 3.4 style change thing.

**Comment by chasegiunta** [comment]
Should be fixed. Give it a spin.

**Comment by chrisrowe** [comment]
Still seeing this in 3.5.0-beta.1

**Comment by chrisrowe** [comment]
`<jason-switch>` isn't being instantiated. I can't see anything in there preventing these just being `forms.lightswitchField` ?

**Comment by chasegiunta** [comment]
If it’s not being instantiated then the entire plugin will be broke on 3.5

**Comment by chrisrowe** [comment]
The field seems to work on an entry page after I manually set `readonly`etc when configuring the field
