### ISSUE TITLE
Edit fields not showing in Matrix field

### ISSUE THREAD

**Issue by kristoffeys** [chasegiunta/craft-jason#76]
When this plugin is used within a matrix field, only the last time it is used is rendered.
This is caused by the id's used to fill the `window.JasonField` object are the same for all fields:
![image](https://user-images.githubusercontent.com/2085632/81223324-1f623000-8fe6-11ea-8913-394e6a2d1e7b.png)

When i change this to use the namespace as key instead, it works as desired:
![image](https://user-images.githubusercontent.com/2085632/81223279-0c4f6000-8fe6-11ea-92ca-323c235810ef.png)

I will prepare a PR that implements this, is this a desired solution?

**Comment by chasegiunta** [comment]
Hi @kristoffeys - thanks for digging into this. Just letting you know I'm going to have a new version of Jason out very soon, with this fix included.

**Comment by kristoffeys** [comment]
great, thanks for the update!

**Comment by chasegiunta** [comment]
Should be fixed in new release @kristoffeys - give it a spin when you get a chance!
